### ISSUE TITLE
Reporte técnico

### ISSUE THREAD

**Issue by reginagarciah** [reginagarciah/parcial-1-#1]
- Introducción
Visión general del proyecto 

- Descripción del problema
Descripción general de lo que son voltajes, resistencias, corrientes y otros componentes de los circuitos eléctricos. Fórmulas y maneras de calcularlos y para qué sirven. 

- Resultados 
Validación de resultados en Excel y Matlab

- Conclusiones 
Aprendizajes del proyecto

**Comment by CarlosGalinndo** [comment]
[REPORTE TECNICO.pdf](https://github.com/reginagarciah/parcial-1-/files/7162740/REPORTE.TECNICO.pdf)
