### ISSUE TITLE
Investigación

### ISSUE THREAD

**Issue by laumtz21** [reginagarciah/parcial-1-#6]
Espacio donde se colocaran los screenshoots y códigos fuente de la investigación
1. [Investigacion_ Introduccion a la Inteligencia artificial (1).pdf](https://github.com/reginagarciah/parcial-1-/files/7150785/Investigacion_.Introduccion.a.la.Inteligencia.artificial.1.pdf)

**Comment by panquique** [comment]
[Investigación en Bioinformática.pdf](https://github.com/reginagarciah/parcial-1-/files/7161097/Investigacion.en.Bioinformatica.pdf)
